# baseurl: /2017

collections:
  students:
    output: true
    permalink: /:collection/:path/

  categories:
    output: true
    permalink: /:path/


defaults:
  - scope:
      path: ""
      type: students
    values:
      layout: student
  - scope:
      path: ""
      type: categories
    values:
      layout: category
