# baseurl: /2017

exclude:
  - app
  - Gemfile
  - Gemfile.LOCK
  - package.json
  - yarn.lock
  - webpack.config.js
  - notes.md
  - node_modules

collections:
  students:
    output: true
    permalink: /:collection/:path/

  categories:
    output: true
    permalink: /:path/


defaults:
  - scope:
      path: ""
      type: students
    values:
      layout: student
  - scope:
      path: ""
      type: categories
    values:
      layout: category
